// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rqr_ecm_intercept_run_cpp
Rcpp::List rqr_ecm_intercept_run_cpp(const Rcpp::NumericVector& y, const double coverage_level, const double learning_rate, const Rcpp::NumericVector& mean_tilt, const double prior_prec, const double beta1_start, const double beta2_start, const int max_iter, const double tol_objective, const double tol_parameters, const double tol_stationarity, const int stable_iterations, const double residual_product_floor, const Rcpp::NumericVector& floor_schedule, const std::string floor_type, const bool monotone_backtracking, const int backtracking_max_steps, const double monotone_tolerance, const bool canonicalize_complete_roots, const std::string start_label);
RcppExport SEXP _rqrgibbs_rqr_ecm_intercept_run_cpp(SEXP ySEXP, SEXP coverage_levelSEXP, SEXP learning_rateSEXP, SEXP mean_tiltSEXP, SEXP prior_precSEXP, SEXP beta1_startSEXP, SEXP beta2_startSEXP, SEXP max_iterSEXP, SEXP tol_objectiveSEXP, SEXP tol_parametersSEXP, SEXP tol_stationaritySEXP, SEXP stable_iterationsSEXP, SEXP residual_product_floorSEXP, SEXP floor_scheduleSEXP, SEXP floor_typeSEXP, SEXP monotone_backtrackingSEXP, SEXP backtracking_max_stepsSEXP, SEXP monotone_toleranceSEXP, SEXP canonicalize_complete_rootsSEXP, SEXP start_labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type coverage_level(coverage_levelSEXP);
    Rcpp::traits::input_parameter< const double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mean_tilt(mean_tiltSEXP);
    Rcpp::traits::input_parameter< const double >::type prior_prec(prior_precSEXP);
    Rcpp::traits::input_parameter< const double >::type beta1_start(beta1_startSEXP);
    Rcpp::traits::input_parameter< const double >::type beta2_start(beta2_startSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_objective(tol_objectiveSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_parameters(tol_parametersSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_stationarity(tol_stationaritySEXP);
    Rcpp::traits::input_parameter< const int >::type stable_iterations(stable_iterationsSEXP);
    Rcpp::traits::input_parameter< const double >::type residual_product_floor(residual_product_floorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type floor_schedule(floor_scheduleSEXP);
    Rcpp::traits::input_parameter< const std::string >::type floor_type(floor_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type monotone_backtracking(monotone_backtrackingSEXP);
    Rcpp::traits::input_parameter< const int >::type backtracking_max_steps(backtracking_max_stepsSEXP);
    Rcpp::traits::input_parameter< const double >::type monotone_tolerance(monotone_toleranceSEXP);
    Rcpp::traits::input_parameter< const bool >::type canonicalize_complete_roots(canonicalize_complete_rootsSEXP);
    Rcpp::traits::input_parameter< const std::string >::type start_label(start_labelSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_ecm_intercept_run_cpp(y, coverage_level, learning_rate, mean_tilt, prior_prec, beta1_start, beta2_start, max_iter, tol_objective, tol_parameters, tol_stationarity, stable_iterations, residual_product_floor, floor_schedule, floor_type, monotone_backtracking, backtracking_max_steps, monotone_tolerance, canonicalize_complete_roots, start_label));
    return rcpp_result_gen;
END_RCPP
}
// rqr_mvn_draw_cpp
Rcpp::List rqr_mvn_draw_cpp(const arma::vec& mean, const arma::mat& covariance, const arma::vec& jitter_ladder, const bool allow_repair);
RcppExport SEXP _rqrgibbs_rqr_mvn_draw_cpp(SEXP meanSEXP, SEXP covarianceSEXP, SEXP jitter_ladderSEXP, SEXP allow_repairSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jitter_ladder(jitter_ladderSEXP);
    Rcpp::traits::input_parameter< const bool >::type allow_repair(allow_repairSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_mvn_draw_cpp(mean, covariance, jitter_ladder, allow_repair));
    return rcpp_result_gen;
END_RCPP
}
// rqr_filter_log_marginal_cpp
double rqr_filter_log_marginal_cpp(const arma::vec& z, const arma::mat& H, const arma::vec& V, const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const arma::cube& W);
RcppExport SEXP _rqrgibbs_rqr_filter_log_marginal_cpp(SEXP zSEXP, SEXP HSEXP, SEXP VSEXP, SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_filter_log_marginal_cpp(z, H, V, GG, m0, C0, W));
    return rcpp_result_gen;
END_RCPP
}
// rqr_ffbs_cpp
Rcpp::List rqr_ffbs_cpp(const arma::vec& z, const arma::mat& H, const arma::vec& V, const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const int evolution_mode, const arma::cube& W, const arma::mat& D, const bool sample_path, const arma::vec& jitter_ladder, const arma::mat& canonical_shift, const std::string evolution_label, const bool allow_covariance_repair);
RcppExport SEXP _rqrgibbs_rqr_ffbs_cpp(SEXP zSEXP, SEXP HSEXP, SEXP VSEXP, SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP evolution_modeSEXP, SEXP WSEXP, SEXP DSEXP, SEXP sample_pathSEXP, SEXP jitter_ladderSEXP, SEXP canonical_shiftSEXP, SEXP evolution_labelSEXP, SEXP allow_covariance_repairSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const int >::type evolution_mode(evolution_modeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_path(sample_pathSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jitter_ladder(jitter_ladderSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type canonical_shift(canonical_shiftSEXP);
    Rcpp::traits::input_parameter< const std::string >::type evolution_label(evolution_labelSEXP);
    Rcpp::traits::input_parameter< const bool >::type allow_covariance_repair(allow_covariance_repairSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_ffbs_cpp(z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, canonical_shift, evolution_label, allow_covariance_repair));
    return rcpp_result_gen;
END_RCPP
}
// rqr_noncentered_basis_cpp
Rcpp::List rqr_noncentered_basis_cpp(const arma::mat& theta, const arma::vec& theta0, const arma::cube& GG, const Rcpp::IntegerVector& component_dims, const arma::vec& q);
RcppExport SEXP _rqrgibbs_rqr_noncentered_basis_cpp(SEXP thetaSEXP, SEXP theta0SEXP, SEXP GGSEXP, SEXP component_dimsSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type component_dims(component_dimsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_noncentered_basis_cpp(theta, theta0, GG, component_dims, q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rqrgibbs_rqr_ecm_intercept_run_cpp", (DL_FUNC) &_rqrgibbs_rqr_ecm_intercept_run_cpp, 20},
    {"_rqrgibbs_rqr_mvn_draw_cpp", (DL_FUNC) &_rqrgibbs_rqr_mvn_draw_cpp, 4},
    {"_rqrgibbs_rqr_filter_log_marginal_cpp", (DL_FUNC) &_rqrgibbs_rqr_filter_log_marginal_cpp, 7},
    {"_rqrgibbs_rqr_ffbs_cpp", (DL_FUNC) &_rqrgibbs_rqr_ffbs_cpp, 14},
    {"_rqrgibbs_rqr_noncentered_basis_cpp", (DL_FUNC) &_rqrgibbs_rqr_noncentered_basis_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rqrgibbs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
