// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rqr_ffbs_cpp
Rcpp::List rqr_ffbs_cpp(const arma::vec& z, const arma::mat& H, const arma::vec& V, const arma::cube& GG, const arma::vec& m0, const arma::mat& C0, const int evolution_mode, const arma::cube& W, const arma::mat& D, const bool sample_path, const arma::vec& jitter_ladder, const std::string evolution_label);
RcppExport SEXP _rqrgibbs_rqr_ffbs_cpp(SEXP zSEXP, SEXP HSEXP, SEXP VSEXP, SEXP GGSEXP, SEXP m0SEXP, SEXP C0SEXP, SEXP evolution_modeSEXP, SEXP WSEXP, SEXP DSEXP, SEXP sample_pathSEXP, SEXP jitter_ladderSEXP, SEXP evolution_labelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type GG(GGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C0(C0SEXP);
    Rcpp::traits::input_parameter< const int >::type evolution_mode(evolution_modeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_path(sample_pathSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type jitter_ladder(jitter_ladderSEXP);
    Rcpp::traits::input_parameter< const std::string >::type evolution_label(evolution_labelSEXP);
    rcpp_result_gen = Rcpp::wrap(rqr_ffbs_cpp(z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, evolution_label));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rqrgibbs_rqr_ffbs_cpp", (DL_FUNC) &_rqrgibbs_rqr_ffbs_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_rqrgibbs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
