# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ intercept-only fixed-target MTI-ECM start
#'
#' @keywords internal
rqr_ecm_intercept_run_cpp <- function(y, coverage_level, learning_rate, mean_tilt, prior_prec, beta1_start, beta2_start, max_iter, tol_objective, tol_parameters, tol_stationarity, stable_iterations, residual_product_floor, floor_schedule, floor_type, monotone_backtracking, backtracking_max_steps, monotone_tolerance, canonicalize_complete_roots, start_label) {
    .Call(`_rqrgibbs_rqr_ecm_intercept_run_cpp`, y, coverage_level, learning_rate, mean_tilt, prior_prec, beta1_start, beta2_start, max_iter, tol_objective, tol_parameters, tol_stationarity, stable_iterations, residual_product_floor, floor_schedule, floor_type, monotone_backtracking, backtracking_max_steps, monotone_tolerance, canonicalize_complete_roots, start_label)
}

#' C++ Gaussian covariance-draw diagnostic kernel
#'
#' @keywords internal
rqr_mvn_draw_cpp <- function(mean, covariance, jitter_ladder, allow_repair) {
    .Call(`_rqrgibbs_rqr_mvn_draw_cpp`, mean, covariance, jitter_ladder, allow_repair)
}

#' C++ scalar-observation Gaussian filter log marginal
#'
#' This deterministic filter is used by an exact partially collapsed
#' component-scale transition. It performs no covariance repair and consumes
#' no random numbers.
#'
#' @keywords internal
rqr_filter_log_marginal_cpp <- function(z, H, V, GG, m0, C0, W) {
    .Call(`_rqrgibbs_rqr_filter_log_marginal_cpp`, z, H, V, GG, m0, C0, W)
}

#' C++ scalar-observation FFBS kernel
#'
#' @keywords internal
rqr_ffbs_cpp <- function(z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, canonical_shift, evolution_label, allow_covariance_repair) {
    .Call(`_rqrgibbs_rqr_ffbs_cpp`, z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, canonical_shift, evolution_label, allow_covariance_repair)
}

rqr_noncentered_basis_cpp <- function(theta, theta0, GG, component_dims, q) {
    .Call(`_rqrgibbs_rqr_noncentered_basis_cpp`, theta, theta0, GG, component_dims, q)
}

