# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ Gaussian covariance-draw diagnostic kernel
#'
#' @keywords internal
rqr_mvn_draw_cpp <- function(mean, covariance, jitter_ladder, allow_repair) {
    .Call(`_rqrgibbs_rqr_mvn_draw_cpp`, mean, covariance, jitter_ladder, allow_repair)
}

#' C++ scalar-observation FFBS kernel
#'
#' @keywords internal
rqr_ffbs_cpp <- function(z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, evolution_label, allow_covariance_repair) {
    .Call(`_rqrgibbs_rqr_ffbs_cpp`, z, H, V, GG, m0, C0, evolution_mode, W, D, sample_path, jitter_ladder, evolution_label, allow_covariance_repair)
}

